### ISSUE TITLE
strings, symbols, and computed keys?

### ISSUE THREAD

**Issue by ljharb** [devlato/tc39-proposal-key-exclusion-syntax-in-object-spread#5]
I think you'll probably have to also support `-[key]` syntax, so that Symbols and computed keys work, and probably also `-'foo bar'` for string keys that aren't identifier names.

**Comment by devlato** [comment]
@ljharb thanks for your comment! The [older edition](https://github.com/devlato/tc39-proposal-key-exclusion-syntax-in-object-spread/blob/5b5d38235f0a80b1d10cd7427fd4021e232a255c/README.md) of this proposal covered these—it turns out I forgot to add them in the new edition! Will update shortly.

Update: it's [done](https://github.com/devlato/tc39-proposal-key-exclusion-syntax-in-object-spread)—thanks!

**Comment by ljharb** [comment]
Ok - https://github.com/devlato/tc39-proposal-key-exclusion-syntax-in-object-spread#5-excluding-multiple-keys-dynamically is an entirely distinct feature that seems confusing to me with the double meaning of brackets, but that can be discussed in a separate issue.

**Comment by devlato** [comment]
> is an entirely distinct feature that seems confusing to me with the double meaning of brackets, but that can be discussed in a separate issue

Yeah basically I see the value in allowing for removing multiple dymanic keys at once, but the proposed indeed isn't the best. I think I'll probably just graveyard that section for now
